# Generated by Django 5.1.15 on 2026-06-10 13:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPartner',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='거래처코드')),
                ('name', models.CharField(max_length=120, verbose_name='거래처명')),
                ('biz_class', models.CharField(choices=[('customer', '매출처'), ('vendor', '매입처'), ('both', '매출+매입')], default='customer', max_length=12, verbose_name='거래처 구분')),
                ('biz_no', models.CharField(blank=True, max_length=20, verbose_name='사업자등록번호')),
                ('rep_name', models.CharField(blank=True, max_length=60, verbose_name='대표자')),
                ('biz_kind', models.CharField(blank=True, max_length=60, verbose_name='업태')),
                ('biz_item', models.CharField(blank=True, max_length=60, verbose_name='종목')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='사업장주소')),
                ('tel', models.CharField(blank=True, max_length=40, verbose_name='전화번호')),
                ('fax', models.CharField(blank=True, max_length=40, verbose_name='팩스번호')),
                ('email', models.EmailField(blank=True, max_length=120, verbose_name='이메일')),
                ('vat_type', models.CharField(choices=[('vat', 'VAT 포함'), ('none', 'VAT 없음')], default='none', max_length=10, verbose_name='VAT 기본값')),
                ('output_name', models.CharField(blank=True, max_length=120, verbose_name='출력용 거래처명')),
                ('memo', models.TextField(blank=True, verbose_name='비고')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company', verbose_name='소속 회사')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 거래처',
                'verbose_name_plural': 'historical 거래처',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='거래처코드')),
                ('name', models.CharField(max_length=120, verbose_name='거래처명')),
                ('biz_class', models.CharField(choices=[('customer', '매출처'), ('vendor', '매입처'), ('both', '매출+매입')], default='customer', max_length=12, verbose_name='거래처 구분')),
                ('biz_no', models.CharField(blank=True, max_length=20, verbose_name='사업자등록번호')),
                ('rep_name', models.CharField(blank=True, max_length=60, verbose_name='대표자')),
                ('biz_kind', models.CharField(blank=True, max_length=60, verbose_name='업태')),
                ('biz_item', models.CharField(blank=True, max_length=60, verbose_name='종목')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='사업장주소')),
                ('tel', models.CharField(blank=True, max_length=40, verbose_name='전화번호')),
                ('fax', models.CharField(blank=True, max_length=40, verbose_name='팩스번호')),
                ('email', models.EmailField(blank=True, max_length=120, verbose_name='이메일')),
                ('vat_type', models.CharField(choices=[('vat', 'VAT 포함'), ('none', 'VAT 없음')], default='none', max_length=10, verbose_name='VAT 기본값')),
                ('output_name', models.CharField(blank=True, max_length=120, verbose_name='출력용 거래처명')),
                ('memo', models.TextField(blank=True, verbose_name='비고')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='companies.company', verbose_name='소속 회사')),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPartnerAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bank', models.CharField(max_length=40, verbose_name='은행')),
                ('account_no', models.CharField(max_length=60, verbose_name='계좌번호')),
                ('holder', models.CharField(blank=True, max_length=60, verbose_name='예금주')),
                ('nickname', models.CharField(blank=True, max_length=60, verbose_name='계좌별칭')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 계좌')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': 'historical 거래처 계좌',
                'verbose_name_plural': 'historical 거래처 계좌',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=40, verbose_name='은행')),
                ('account_no', models.CharField(max_length=60, verbose_name='계좌번호')),
                ('holder', models.CharField(blank=True, max_length=60, verbose_name='예금주')),
                ('nickname', models.CharField(blank=True, max_length=60, verbose_name='계좌별칭')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 계좌')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='partners.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '거래처 계좌',
                'verbose_name_plural': '거래처 계좌',
                'ordering': ['-is_default', 'bank'],
            },
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['company', 'name'], name='partners_pa_company_6f9b05_idx'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_partner_company_code'),
        ),
    ]
