# Generated by Django 5.1.15 on 2026-06-10 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_form', models.CharField(choices=[('plain1', '순백지1'), ('plain2', '순백지2'), ('plain3', '순백지3'), ('plain4', '순백지4')], default='plain4', max_length=10, verbose_name='인쇄형태')),
                ('show_supplier_seal', models.BooleanField(default=True, verbose_name='1. 공급자란 인쇄')),
                ('show_delivery_addr', models.BooleanField(default=True, verbose_name='2. 배송지주소')),
                ('show_qty_total', models.BooleanField(default=True, verbose_name='3. 수량계 인쇄')),
                ('show_vat', models.BooleanField(default=True, verbose_name='4. 부가가치세 표시')),
                ('show_decimal', models.BooleanField(default=True, verbose_name='5. 소수점 표시')),
                ('show_qty', models.BooleanField(default=True, verbose_name='6. 수량 표시')),
                ('show_unit_price', models.BooleanField(default=True, verbose_name='7. 단가 표시')),
                ('show_amount', models.BooleanField(default=True, verbose_name='8. 금액 표시')),
                ('show_total_amount', models.BooleanField(default=True, verbose_name='9. 합계금액 표시')),
                ('show_receivable', models.BooleanField(default=False, verbose_name='10. 채권 표시')),
                ('representative_type', models.CharField(choices=[('supplier', '1. 공급자'), ('partner_b', '2. 거래처-기초'), ('partner_a', '3. 거래처-추가'), ('delivery', '4. 배송지')], default='supplier', max_length=12, verbose_name='11. 담당자 인쇄')),
                ('show_item_memo', models.BooleanField(default=True, verbose_name='12. 품목비고 표시')),
                ('invoice_memo_field', models.CharField(choices=[('memo1', '1. 비고1'), ('memo2', '2. 비고2'), ('memo3', '3. 비고3'), ('all', '4. 전체')], default='memo1', max_length=10, verbose_name='13. 거래명세서비고 표시')),
                ('show_spec', models.BooleanField(default=True, verbose_name='14. 규격 표시')),
                ('show_tax_amount', models.BooleanField(default=True, verbose_name='15. 순백지1,2 세액 표시')),
                ('show_today_total', models.BooleanField(default=True, verbose_name='16. 당일거래총액 표시')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='companies.company', verbose_name='회사')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '명세서 설정',
                'verbose_name_plural': '명세서 설정',
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='uq_invoice_setting_user_company')],
            },
        ),
    ]
