# Generated by Django 5.1.15 on 2026-06-10 13:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='품목코드')),
                ('name', models.CharField(max_length=120, verbose_name='품명')),
                ('spec', models.CharField(blank=True, max_length=60, verbose_name='규격')),
                ('procure_type', models.CharField(choices=[('buy', '구매품'), ('make', '생산품'), ('subcontract', '외주')], default='buy', max_length=12, verbose_name='조달구분')),
                ('account_type', models.CharField(choices=[('product', '상품'), ('material', '원재료'), ('sub_material', '부재료'), ('manufactured', '제품'), ('semi', '반제품'), ('byproduct', '부산품'), ('storage', '저장품')], default='product', max_length=14, verbose_name='품목계정')),
                ('unit_in', models.CharField(default='kg', max_length=10, verbose_name='입고단위')),
                ('unit_out', models.CharField(default='kg', max_length=10, verbose_name='출고단위')),
                ('unit_stock', models.CharField(default='kg', max_length=10, verbose_name='재고단위')),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='표준원가')),
                ('invoice_print_name', models.CharField(blank=True, max_length=120, verbose_name='거래명세서 출력명')),
                ('memo', models.TextField(blank=True, verbose_name='비고')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company', verbose_name='소속 회사')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 품목',
                'verbose_name_plural': 'historical 품목',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='품목코드')),
                ('name', models.CharField(max_length=120, verbose_name='품명')),
                ('spec', models.CharField(blank=True, max_length=60, verbose_name='규격')),
                ('procure_type', models.CharField(choices=[('buy', '구매품'), ('make', '생산품'), ('subcontract', '외주')], default='buy', max_length=12, verbose_name='조달구분')),
                ('account_type', models.CharField(choices=[('product', '상품'), ('material', '원재료'), ('sub_material', '부재료'), ('manufactured', '제품'), ('semi', '반제품'), ('byproduct', '부산품'), ('storage', '저장품')], default='product', max_length=14, verbose_name='품목계정')),
                ('unit_in', models.CharField(default='kg', max_length=10, verbose_name='입고단위')),
                ('unit_out', models.CharField(default='kg', max_length=10, verbose_name='출고단위')),
                ('unit_stock', models.CharField(default='kg', max_length=10, verbose_name='재고단위')),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='표준원가')),
                ('invoice_print_name', models.CharField(blank=True, max_length=120, verbose_name='거래명세서 출력명')),
                ('memo', models.TextField(blank=True, verbose_name='비고')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='companies.company', verbose_name='소속 회사')),
            ],
            options={
                'verbose_name': '품목',
                'verbose_name_plural': '품목',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['company', 'name'], name='items_item_company_f46c7b_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uq_item_company_code')],
            },
        ),
    ]
