# Generated by Django 5.1.15 on 2026-06-21 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('items', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='partner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='이 품목이 속한 거래처. 신규 품목은 필수, 기존 데이터는 NULL 허용.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partner', verbose_name='거래처'),
        ),
        migrations.AddField(
            model_name='item',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='이 품목이 속한 거래처. 신규 품목은 필수, 기존 데이터는 NULL 허용.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplied_items', to='partners.partner', verbose_name='거래처'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'partner'], name='items_item_company_e67afd_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('company', 'partner', 'name'), name='uq_item_company_partner_name'),
        ),
    ]
