# Generated by Django 5.1.15 on 2026-06-10 13:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCollection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('receipt_no', models.CharField(db_index=True, max_length=24, verbose_name='수금번호')),
                ('receipt_date', models.DateField(verbose_name='수금일자')),
                ('receipt_type', models.CharField(choices=[('cash', '현금'), ('deposit', '예금'), ('card', '카드'), ('note', '어음'), ('discount_prod', '할인(상품)'), ('discount_made', '할인(제품)'), ('prepay_cash', '선수금(현금)'), ('prepay_dep', '선수금(예금)'), ('prepay_clear', '선수금정리'), ('offset', '상계'), ('misc_loss', '잡손실'), ('misc_gain', '잡이익')], default='cash', max_length=20, verbose_name='수금유형')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='금액')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='적요')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partneraccount', verbose_name='금융거래처')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company', verbose_name='회사')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': 'historical 수금',
                'verbose_name_plural': 'historical 수금',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=24, unique=True, verbose_name='수금번호')),
                ('receipt_date', models.DateField(verbose_name='수금일자')),
                ('receipt_type', models.CharField(choices=[('cash', '현금'), ('deposit', '예금'), ('card', '카드'), ('note', '어음'), ('discount_prod', '할인(상품)'), ('discount_made', '할인(제품)'), ('prepay_cash', '선수금(현금)'), ('prepay_dep', '선수금(예금)'), ('prepay_clear', '선수금정리'), ('offset', '상계'), ('misc_loss', '잡손실'), ('misc_gain', '잡이익')], default='cash', max_length=20, verbose_name='수금유형')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='금액')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='적요')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='partners.partneraccount', verbose_name='금융거래처')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='companies.company', verbose_name='회사')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='partners.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '수금',
                'verbose_name_plural': '수금',
                'ordering': ['-receipt_date', '-receipt_no'],
                'indexes': [models.Index(fields=['company', '-receipt_date'], name='collections_company_1afb40_idx'), models.Index(fields=['company', 'partner', '-receipt_date'], name='collections_company_dd3bdf_idx')],
            },
        ),
    ]
