# Generated by Django 5.1.15 on 2026-06-10 13:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPartnerPrice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='매출단가')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='매입단가')),
                ('effective_from', models.DateField(help_text='이 단가가 적용되는 시작 날짜. 출고처리는 발주일자 기준으로 가장 최근(이전) 적용일의 단가를 사용합니다.', verbose_name='적용 시작일')),
                ('memo', models.CharField(blank=True, max_length=120, verbose_name='비고')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='items.item', verbose_name='품목')),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': 'historical 거래처별 단가',
                'verbose_name_plural': 'historical 거래처별 단가',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='매출단가')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='매입단가')),
                ('effective_from', models.DateField(help_text='이 단가가 적용되는 시작 날짜. 출고처리는 발주일자 기준으로 가장 최근(이전) 적용일의 단가를 사용합니다.', verbose_name='적용 시작일')),
                ('memo', models.CharField(blank=True, max_length=120, verbose_name='비고')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='items.item', verbose_name='품목')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='partners.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '거래처별 단가',
                'verbose_name_plural': '거래처별 단가',
                'ordering': ['partner', 'item', '-effective_from'],
                'indexes': [models.Index(fields=['partner', 'item', '-effective_from'], name='prices_part_partner_36f895_idx')],
                'constraints': [models.UniqueConstraint(fields=('partner', 'item', 'effective_from'), name='uq_partner_item_from')],
            },
        ),
    ]
