# Generated by Django 5.1.15 on 2026-06-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='회사명')),
                ('biz_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자등록번호')),
                ('rep_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='대표자')),
                ('biz_type', models.CharField(choices=[('법인', '법인'), ('개인', '개인')], default='법인', max_length=10, verbose_name='구분')),
                ('is_default', models.BooleanField(default=False, verbose_name='대표 회사')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '회사',
                'verbose_name_plural': '회사',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
