# Generated by Django 5.1.15 on 2026-06-10 13:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('items', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=24, unique=True, verbose_name='출고번호')),
                ('order_date', models.DateField(verbose_name='출고일자')),
                ('vat_type', models.CharField(choices=[('vat', 'VAT 포함'), ('none', 'VAT 없음')], default='none', max_length=10, verbose_name='VAT 여부')),
                ('tax_type', models.CharField(choices=[('taxable', '과세'), ('exempt', '면세'), ('zero', '영세')], default='exempt', max_length=10, verbose_name='과세구분')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('confirmed', '완료'), ('voided', '취소')], default='confirmed', max_length=12, verbose_name='전표상태')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='적요')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='공급가액 합계')),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='부가세 합계')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='총 합계금액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='companies.company', verbose_name='회사')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='partners.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '출고전표',
                'verbose_name_plural': '출고전표',
                'ordering': ['-order_date', '-order_no'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(blank=True, max_length=60, verbose_name='규격')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='단위')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='단가')),
                ('supply_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='공급가액')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='부가세')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='합계금액')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='비고')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='items.item', verbose_name='품목')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='delivery.deliveryorder', verbose_name='출고전표')),
            ],
            options={
                'verbose_name': '출고 라인',
                'verbose_name_plural': '출고 라인',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeliveryOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=24, verbose_name='출고번호')),
                ('order_date', models.DateField(verbose_name='출고일자')),
                ('vat_type', models.CharField(choices=[('vat', 'VAT 포함'), ('none', 'VAT 없음')], default='none', max_length=10, verbose_name='VAT 여부')),
                ('tax_type', models.CharField(choices=[('taxable', '과세'), ('exempt', '면세'), ('zero', '영세')], default='exempt', max_length=10, verbose_name='과세구분')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('confirmed', '완료'), ('voided', '취소')], default='confirmed', max_length=12, verbose_name='전표상태')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='적요')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='공급가액 합계')),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='부가세 합계')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='총 합계금액')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company', verbose_name='회사')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partner', verbose_name='거래처')),
            ],
            options={
                'verbose_name': 'historical 출고전표',
                'verbose_name_plural': 'historical 출고전표',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['company', '-order_date'], name='delivery_de_company_5b53cc_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['company', 'partner', '-order_date'], name='delivery_de_company_375eec_idx'),
        ),
    ]
